services:
  db:
    env_file:
      - ./environment/db.env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./infra/postgres/init-scripts:/docker-entrypoint-initdb.d
  
  auth_service:
    build:
      context: .
      dockerfile: services/auth/src/main/docker/Dockerfile.custom
      target: development
    env_file:
      - ./environment/shared.env
    ports:
      - "${AUTH_PORT}:8080"
    volumes:
      - ./services/auth:/app

  chat_service:
    build:
      context: .
      dockerfile: services/chat/Dockerfile
      target: development
    env_file:
      - ./environment/shared.env   
    ports:
      - "8081:8080"
    volumes:
      - ./services/chat:/app

  forum_service:
    working_dir: /app
    env_file:
      - ./environment/shared.env
      - ./environment/forum.env
    ports:
      - "${FORUM_PORT}:8000"
    volumes:
      - ./services/forum:/app
    # Note: 'uv run' will install dependencies on the fly in dev if they are in pyproject.toml
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  web_service:
    build:
      context: .
      dockerfile: services/web/Dockerfile
      target: development
    ports:
      - "${WEB_PORT}:3000"
    volumes:
      - ./services/web:/app
    env_file:
      - ./environment/shared.env
      - ./environment/web.env


  # add other services below here, example:
  # redis:
  #   image: redis:7-alpine
  #   container_name: redis_cache
  #   ports:
  #     - "6379:6379"

