quarkus.http.port=8080
quarkus.http.ssl-port=8443

quarkus.http.ssl.certificate.key-store-file=/certs/auth-keystore.p12
quarkus.http.ssl.certificate.key-store-password=bumintra
quarkus.http.ssl.certificate.key-store-file-type=PKCS12

quarkus.http.ssl.client-auth=required

quarkus.http.ssl.certificate.trust-store-file=/certs/shared-truststore.p12
quarkus.http.ssl.certificate.trust-store-password=bumintra
quarkus.http.ssl.certificate.trust-store-file-type=PKCS12
