{
 "title": "42Overflow",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Auth Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"auth\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chat Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"chat\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services Down Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\"auth|chat|forum|gateway|postgres|web\"} == bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "description": "Current active alerts for service down",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "targets": [
    { "expr": "ALERTS", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Forum Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"forum\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"web\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services History",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "up{job=~\"auth|forum|chat|gateway|postgres|web\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Gateway Total Request (5min)",
   "type": "stat",
   "description": "Total request of last 5min",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gateway_http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Total Success Request (5min)",
   "type": "stat",
   "description": "Total Success request of last 5min",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gateway_http_requests_total{result=\"success\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Total Failed Request (5min)",
   "type": "stat",
   "description": "Total failed request of last 5min",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gateway_http_errors_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by Code (5min)",
   "type": "bargauge",
   "description": "Result based on last 5min",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(error_code) (increase(gateway_http_errors_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by Services (5min)",
   "type": "bargauge",
   "description": "Result based on last 5min",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (increase(gateway_http_errors_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}