# --- Database Connection ---
quarkus.datasource.db-kind=postgresql
#username and pass below defaults to dev_user and dev_password if env not found. to remove later
quarkus.datasource.username=${DB_USER:dev_user}
quarkus.datasource.password=${DB_PASSWORD:dev_password}
# Connect to the 'db' service defined in docker-compose
quarkus.datasource.jdbc.url=jdbc:postgresql://db:5432/postgres_db

# --- Schema Isolation ---
# ensures Chat Service ONLY sees the 'chat_service' schema
quarkus.datasource.jdbc.schema=chat_service

# --- Hibernate (ORM) ---
# 'update': Auto-creates tables based on your @Entity classes
quarkus.hibernate-orm.database-generation=validate
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file

# --- HTTP Server ---
# Run on port 8080 (internally), we map it to 8002 in Docker
quarkus.http.port=8080

quarkus.application.name=chat
