// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"createdAt"`
	Id         int       `json:"id"`
	ReceiverId int       `json:"receiverId"`
	SenderId   int       `json:"senderId"`
}

// SendMessageJSONBody defines parameters for SendMessage.
type SendMessageJSONBody struct {
	Content string `json:"content"`
}

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody SendMessageJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Send a friend request
	// (POST /friendship/{requesterId}/{receiverId})
	SendFriendRequest(w http.ResponseWriter, r *http.Request, requesterId int, receiverId int)
	// Accept a friend request
	// (PATCH /friendship/{requesterId}/{receiverId}/accept)
	AcceptFriendRequest(w http.ResponseWriter, r *http.Request, requesterId int, receiverId int)
	// Get chat history between two users
	// (GET /message/history/{senderId}/{receiverId})
	GetMessageHistory(w http.ResponseWriter, r *http.Request, senderId int, receiverId int)
	// Opens an SSE connection for real-time chat message updates
	// (GET /message/stream/{tempUserId})
	GetMessageStream(w http.ResponseWriter, r *http.Request, tempUserId int)
	// Send a chat message
	// (POST /message/{senderId}/{receiverId})
	SendMessage(w http.ResponseWriter, r *http.Request, senderId int, receiverId int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Send a friend request
// (POST /friendship/{requesterId}/{receiverId})
func (_ Unimplemented) SendFriendRequest(w http.ResponseWriter, r *http.Request, requesterId int, receiverId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Accept a friend request
// (PATCH /friendship/{requesterId}/{receiverId}/accept)
func (_ Unimplemented) AcceptFriendRequest(w http.ResponseWriter, r *http.Request, requesterId int, receiverId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get chat history between two users
// (GET /message/history/{senderId}/{receiverId})
func (_ Unimplemented) GetMessageHistory(w http.ResponseWriter, r *http.Request, senderId int, receiverId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Opens an SSE connection for real-time chat message updates
// (GET /message/stream/{tempUserId})
func (_ Unimplemented) GetMessageStream(w http.ResponseWriter, r *http.Request, tempUserId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send a chat message
// (POST /message/{senderId}/{receiverId})
func (_ Unimplemented) SendMessage(w http.ResponseWriter, r *http.Request, senderId int, receiverId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SendFriendRequest operation middleware
func (siw *ServerInterfaceWrapper) SendFriendRequest(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "requesterId" -------------
	var requesterId int

	err = runtime.BindStyledParameterWithOptions("simple", "requesterId", chi.URLParam(r, "requesterId"), &requesterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "requesterId", Err: err})
		return
	}

	// ------------- Path parameter "receiverId" -------------
	var receiverId int

	err = runtime.BindStyledParameterWithOptions("simple", "receiverId", chi.URLParam(r, "receiverId"), &receiverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "receiverId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendFriendRequest(w, r, requesterId, receiverId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptFriendRequest operation middleware
func (siw *ServerInterfaceWrapper) AcceptFriendRequest(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "requesterId" -------------
	var requesterId int

	err = runtime.BindStyledParameterWithOptions("simple", "requesterId", chi.URLParam(r, "requesterId"), &requesterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "requesterId", Err: err})
		return
	}

	// ------------- Path parameter "receiverId" -------------
	var receiverId int

	err = runtime.BindStyledParameterWithOptions("simple", "receiverId", chi.URLParam(r, "receiverId"), &receiverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "receiverId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptFriendRequest(w, r, requesterId, receiverId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMessageHistory operation middleware
func (siw *ServerInterfaceWrapper) GetMessageHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "senderId" -------------
	var senderId int

	err = runtime.BindStyledParameterWithOptions("simple", "senderId", chi.URLParam(r, "senderId"), &senderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "senderId", Err: err})
		return
	}

	// ------------- Path parameter "receiverId" -------------
	var receiverId int

	err = runtime.BindStyledParameterWithOptions("simple", "receiverId", chi.URLParam(r, "receiverId"), &receiverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "receiverId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessageHistory(w, r, senderId, receiverId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMessageStream operation middleware
func (siw *ServerInterfaceWrapper) GetMessageStream(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tempUserId" -------------
	var tempUserId int

	err = runtime.BindStyledParameterWithOptions("simple", "tempUserId", chi.URLParam(r, "tempUserId"), &tempUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tempUserId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessageStream(w, r, tempUserId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendMessage operation middleware
func (siw *ServerInterfaceWrapper) SendMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "senderId" -------------
	var senderId int

	err = runtime.BindStyledParameterWithOptions("simple", "senderId", chi.URLParam(r, "senderId"), &senderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "senderId", Err: err})
		return
	}

	// ------------- Path parameter "receiverId" -------------
	var receiverId int

	err = runtime.BindStyledParameterWithOptions("simple", "receiverId", chi.URLParam(r, "receiverId"), &receiverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "receiverId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendMessage(w, r, senderId, receiverId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/friendship/{requesterId}/{receiverId}", wrapper.SendFriendRequest)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/friendship/{requesterId}/{receiverId}/accept", wrapper.AcceptFriendRequest)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/message/history/{senderId}/{receiverId}", wrapper.GetMessageHistory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/message/stream/{tempUserId}", wrapper.GetMessageStream)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/message/{senderId}/{receiverId}", wrapper.SendMessage)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9yWzZLbNgzHX4WD9uhdaZ2dfui2bdPUM/3I1M2lmT0wFGwxY5EsCTlxPXr3DijJS63k",
	"xjvbQ9ubLZJ/AviBAI6gbO2sQUMBiiMEVWEt489vK0k/YQhyi/zXeevQk8a4qKwhNMQ/6eAQCgjktdlC",
	"uwDlURKWd3EVP8ra7XjDMl9+cZW/uMq//i3/qljeFssvf4cFbKyvJUEBpSS8Il0jLKaaukyu0oZwi56/",
	"e1So9+hXZ9YDmvLcajz+R6M9llC85SuS/SPpxcnf1Lv7k5323XtUBC1LarOxfFuJQXntSFsDBdy9XomN",
	"9aKWRm612Yq6i2wQ0pRi4zWaMlTaBXZeUwwYAxBr9HutUNy9XsEC9uhDJ3hznV/n7KF1aKTTUMCL6/z6",
	"FhbgJFURUvagmx3ZVQzE/rT8b3CujXBtiLQYsWSTOWKwRlN+HyV+7Q5HcS9rJPQBirdH0GwLXwgLMLJm",
	"s5OLII0w+QYXfYLN4zgjl2B4gto97w7OmtBl7DK/mWLpvBO9ySKgIREapTCETbPbHTjAt3k+Pbgye7nT",
	"pWgCerH6LnQbb6cb3/AGY0lsbGPKmHShqWvpD32AhezxD1ZwBsgth7c3j/nBPZ+8DGgmlUIXeTpJqpqC",
	"vYsb/kdo80+i7WKC5QzeGWp9UM6C6wL4JHT9g88qHcj6Q3YcSs30NW5x5jG+wqEa/9ApXERsVM/+XbiS",
	"FiKd22kVfc3eByZwTAQ1YR0Pfu5xAwV8lj30rKxvWFnardpTYZbey0NXl8eAY23tUQiP5DXuZ5PjOW//",
	"ZytUes9cJr1CGm96h/QB0Qj6YOMNIUmqwcFxRgXyKOvsSFg7LjeXZdE6nrooiR6E/2nwhB8pwz0auuq8",
	"GJO/GPgU8Hr9UihrDCr+kIDtaM30gjdGNlRZr//Ex5B+cWi4U4tHqtzRPcpdHFs6jD0U0TieZz4N72/K",
	"wPmmPEj9pypArJDf2PLwpMd/duystfkRzZYqKG4mA+Oj0W44Nj+xjR1pL5kbegDPGBgED4O9ymDe7HCQ",
	"ZtV8NrWnr48vfWlKZ7WhMJ49x+NmzzZpWEz/IqHUtkTq9Czv278CAAD//+n0KfNgDAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
