// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	GatewayUserHeaderScopes = "GatewayUserHeader.Scopes"
)

// Defines values for ChatRoomType.
const (
	Direct ChatRoomType = "direct"
	Group  ChatRoomType = "group"
)

// Valid indicates whether the value is a known member of the ChatRoomType enum.
func (e ChatRoomType) Valid() bool {
	switch e {
	case Direct:
		return true
	case Group:
		return true
	default:
		return false
	}
}

// Defines values for PendingFriendRequestStatus.
const (
	PendingFriendRequestStatusPending PendingFriendRequestStatus = "pending"
)

// Valid indicates whether the value is a known member of the PendingFriendRequestStatus enum.
func (e PendingFriendRequestStatus) Valid() bool {
	switch e {
	case PendingFriendRequestStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for StreamEventType.
const (
	NEWMESSAGE StreamEventType = "NEW_MESSAGE"
	USERREAD   StreamEventType = "USER_READ"
	USERSTATUS StreamEventType = "USER_STATUS"
	USERTYPING StreamEventType = "USER_TYPING"
)

// Valid indicates whether the value is a known member of the StreamEventType enum.
func (e StreamEventType) Valid() bool {
	switch e {
	case NEWMESSAGE:
		return true
	case USERREAD:
		return true
	case USERSTATUS:
		return true
	case USERTYPING:
		return true
	default:
		return false
	}
}

// Defines values for UpdateFriendshipStatusParamsStatus.
const (
	UpdateFriendshipStatusParamsStatusAccepted UpdateFriendshipStatusParamsStatus = "accepted"
	UpdateFriendshipStatusParamsStatusBlocked  UpdateFriendshipStatusParamsStatus = "blocked"
	UpdateFriendshipStatusParamsStatusDeclined UpdateFriendshipStatusParamsStatus = "declined"
	UpdateFriendshipStatusParamsStatusNone     UpdateFriendshipStatusParamsStatus = "none"
	UpdateFriendshipStatusParamsStatusPending  UpdateFriendshipStatusParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the UpdateFriendshipStatusParamsStatus enum.
func (e UpdateFriendshipStatusParamsStatus) Valid() bool {
	switch e {
	case UpdateFriendshipStatusParamsStatusAccepted:
		return true
	case UpdateFriendshipStatusParamsStatusBlocked:
		return true
	case UpdateFriendshipStatusParamsStatusDeclined:
		return true
	case UpdateFriendshipStatusParamsStatusNone:
		return true
	case UpdateFriendshipStatusParamsStatusPending:
		return true
	default:
		return false
	}
}

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	ChatId    openapi_types.UUID `json:"chatId"`
	Content   string             `json:"content"`
	CreatedAt time.Time          `json:"createdAt"`
	Id        int                `json:"id"`
	SenderId  int                `json:"senderId"`
}

// ChatRoom defines model for ChatRoom.
type ChatRoom struct {
	ChatId openapi_types.UUID `json:"chatId"`

	// MemberIds List of all user IDs in this chat. Frontend uses this to fetch avatars/names.
	MemberIds *[]int `json:"memberIds,omitempty"`

	// Name Will be null for direct chats
	Name *string      `json:"name,omitempty"`
	Type ChatRoomType `json:"type"`
}

// ChatRoomType defines model for ChatRoom.Type.
type ChatRoomType string

// FriendList defines model for FriendList.
type FriendList = []struct {
	// ChatId Unique identifier for the chat between the user and the friend
	ChatId *openapi_types.UUID `json:"chatId,omitempty"`

	// FriendId Unique identifier for the friend
	FriendId *int `json:"friendId,omitempty"`

	// IsOnline Whether the friend is currently online
	IsOnline *bool `json:"isOnline,omitempty"`
}

// PendingFriendRequest defines model for PendingFriendRequest.
type PendingFriendRequest struct {
	// AddresseeId User who received the friend request
	AddresseeId int `json:"addresseeId"`

	// RequesterId User who sent the friend request
	RequesterId int                        `json:"requesterId"`
	Status      PendingFriendRequestStatus `json:"status"`
}

// PendingFriendRequestStatus defines model for PendingFriendRequest.Status.
type PendingFriendRequestStatus string

// PendingFriendRequestList defines model for PendingFriendRequestList.
type PendingFriendRequestList = []PendingFriendRequest

// ReadReceipt defines model for ReadReceipt.
type ReadReceipt struct {
	ChatId    openapi_types.UUID `json:"chatId"`
	MessageId int                `json:"messageId"`
	UserId    int                `json:"userId"`
}

// StreamEvent defines model for StreamEvent.
type StreamEvent struct {
	// Payload The actual data, structure depends on the event type
	Payload StreamEvent_Payload `json:"payload"`

	// Type The type of event being sent down the stream
	Type StreamEventType `json:"type"`
}

// StreamEvent_Payload The actual data, structure depends on the event type
type StreamEvent_Payload struct {
	union json.RawMessage
}

// StreamEventType The type of event being sent down the stream
type StreamEventType string

// TypingIndicator defines model for TypingIndicator.
type TypingIndicator struct {
	ChatId   openapi_types.UUID `json:"chatId"`
	SenderId int                `json:"senderId"`
}

// UserStatus defines model for UserStatus.
type UserStatus struct {
	// IsOnline Whether the user is now online or offline
	IsOnline bool `json:"isOnline"`

	// UserId The user whose status changed
	UserId int `json:"userId"`
}

// UpdateFriendshipStatusParams defines parameters for UpdateFriendshipStatus.
type UpdateFriendshipStatusParams struct {
	Status UpdateFriendshipStatusParamsStatus `form:"status" json:"status"`
}

// UpdateFriendshipStatusParamsStatus defines parameters for UpdateFriendshipStatus.
type UpdateFriendshipStatusParamsStatus string

// CreateGroupChatJSONBody defines parameters for CreateGroupChat.
type CreateGroupChatJSONBody struct {
	// MemberIds List of user IDs to add to the group
	MemberIds []int `json:"memberIds"`

	// Name Name of the group chat
	Name string `json:"name"`
}

// UpdateReadReceiptJSONBody defines parameters for UpdateReadReceipt.
type UpdateReadReceiptJSONBody struct {
	MessageId int `json:"messageId"`
}

// SendMessageJSONBody defines parameters for SendMessage.
type SendMessageJSONBody struct {
	Content string `json:"content"`
}

// CreateGroupChatJSONRequestBody defines body for CreateGroupChat for application/json ContentType.
type CreateGroupChatJSONRequestBody CreateGroupChatJSONBody

// UpdateReadReceiptJSONRequestBody defines body for UpdateReadReceipt for application/json ContentType.
type UpdateReadReceiptJSONRequestBody UpdateReadReceiptJSONBody

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody SendMessageJSONBody

// AsChatMessage returns the union data inside the StreamEvent_Payload as a ChatMessage
func (t StreamEvent_Payload) AsChatMessage() (ChatMessage, error) {
	var body ChatMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatMessage overwrites any union data inside the StreamEvent_Payload as the provided ChatMessage
func (t *StreamEvent_Payload) FromChatMessage(v ChatMessage) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatMessage performs a merge with any union data inside the StreamEvent_Payload, using the provided ChatMessage
func (t *StreamEvent_Payload) MergeChatMessage(v ChatMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTypingIndicator returns the union data inside the StreamEvent_Payload as a TypingIndicator
func (t StreamEvent_Payload) AsTypingIndicator() (TypingIndicator, error) {
	var body TypingIndicator
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTypingIndicator overwrites any union data inside the StreamEvent_Payload as the provided TypingIndicator
func (t *StreamEvent_Payload) FromTypingIndicator(v TypingIndicator) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTypingIndicator performs a merge with any union data inside the StreamEvent_Payload, using the provided TypingIndicator
func (t *StreamEvent_Payload) MergeTypingIndicator(v TypingIndicator) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsReadReceipt returns the union data inside the StreamEvent_Payload as a ReadReceipt
func (t StreamEvent_Payload) AsReadReceipt() (ReadReceipt, error) {
	var body ReadReceipt
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromReadReceipt overwrites any union data inside the StreamEvent_Payload as the provided ReadReceipt
func (t *StreamEvent_Payload) FromReadReceipt(v ReadReceipt) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeReadReceipt performs a merge with any union data inside the StreamEvent_Payload, using the provided ReadReceipt
func (t *StreamEvent_Payload) MergeReadReceipt(v ReadReceipt) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserStatus returns the union data inside the StreamEvent_Payload as a UserStatus
func (t StreamEvent_Payload) AsUserStatus() (UserStatus, error) {
	var body UserStatus
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserStatus overwrites any union data inside the StreamEvent_Payload as the provided UserStatus
func (t *StreamEvent_Payload) FromUserStatus(v UserStatus) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserStatus performs a merge with any union data inside the StreamEvent_Payload, using the provided UserStatus
func (t *StreamEvent_Payload) MergeUserStatus(v UserStatus) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StreamEvent_Payload) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StreamEvent_Payload) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get friend list for a user with chat ID references
	// (GET /friendship)
	GetFriendList(w http.ResponseWriter, r *http.Request)
	// Get incoming pending friend requests for a user
	// (GET /friendship/pending)
	GetPendingFriendRequests(w http.ResponseWriter, r *http.Request)
	// Send a friend request
	// (POST /friendship/{receiverId})
	SendFriendRequest(w http.ResponseWriter, r *http.Request, receiverId int)
	// Update friendship status
	// (PATCH /friendship/{receiverId}/update)
	UpdateFriendshipStatus(w http.ResponseWriter, r *http.Request, receiverId int, params UpdateFriendshipStatusParams)
	// Create a new group chat
	// (POST /message/group/create)
	CreateGroupChat(w http.ResponseWriter, r *http.Request)
	// Get chat history for a specific chat
	// (GET /message/history/{chatId})
	GetMessageHistory(w http.ResponseWriter, r *http.Request, chatId openapi_types.UUID)
	// Get all chats (direct and group) for a user's inbox
	// (GET /message/inbox)
	GetUserInbox(w http.ResponseWriter, r *http.Request)
	// Update the last read message for a user in a chat
	// (PATCH /message/read/{chatId})
	UpdateReadReceipt(w http.ResponseWriter, r *http.Request, chatId openapi_types.UUID)
	// Opens an SSE connection for real-time functionalities
	// (GET /message/stream)
	GetMessageStream(w http.ResponseWriter, r *http.Request)
	// Send a typing indicator event
	// (POST /message/typing/{chatId})
	SendTypingEvent(w http.ResponseWriter, r *http.Request, chatId openapi_types.UUID)
	// Send a chat message
	// (POST /message/{chatId})
	SendMessage(w http.ResponseWriter, r *http.Request, chatId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get friend list for a user with chat ID references
// (GET /friendship)
func (_ Unimplemented) GetFriendList(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get incoming pending friend requests for a user
// (GET /friendship/pending)
func (_ Unimplemented) GetPendingFriendRequests(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send a friend request
// (POST /friendship/{receiverId})
func (_ Unimplemented) SendFriendRequest(w http.ResponseWriter, r *http.Request, receiverId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update friendship status
// (PATCH /friendship/{receiverId}/update)
func (_ Unimplemented) UpdateFriendshipStatus(w http.ResponseWriter, r *http.Request, receiverId int, params UpdateFriendshipStatusParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new group chat
// (POST /message/group/create)
func (_ Unimplemented) CreateGroupChat(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get chat history for a specific chat
// (GET /message/history/{chatId})
func (_ Unimplemented) GetMessageHistory(w http.ResponseWriter, r *http.Request, chatId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all chats (direct and group) for a user's inbox
// (GET /message/inbox)
func (_ Unimplemented) GetUserInbox(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update the last read message for a user in a chat
// (PATCH /message/read/{chatId})
func (_ Unimplemented) UpdateReadReceipt(w http.ResponseWriter, r *http.Request, chatId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Opens an SSE connection for real-time functionalities
// (GET /message/stream)
func (_ Unimplemented) GetMessageStream(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send a typing indicator event
// (POST /message/typing/{chatId})
func (_ Unimplemented) SendTypingEvent(w http.ResponseWriter, r *http.Request, chatId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send a chat message
// (POST /message/{chatId})
func (_ Unimplemented) SendMessage(w http.ResponseWriter, r *http.Request, chatId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetFriendList operation middleware
func (siw *ServerInterfaceWrapper) GetFriendList(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, GatewayUserHeaderScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFriendList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPendingFriendRequests operation middleware
func (siw *ServerInterfaceWrapper) GetPendingFriendRequests(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, GatewayUserHeaderScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPendingFriendRequests(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendFriendRequest operation middleware
func (siw *ServerInterfaceWrapper) SendFriendRequest(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "receiverId" -------------
	var receiverId int

	err = runtime.BindStyledParameterWithOptions("simple", "receiverId", chi.URLParam(r, "receiverId"), &receiverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "receiverId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, GatewayUserHeaderScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendFriendRequest(w, r, receiverId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateFriendshipStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateFriendshipStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "receiverId" -------------
	var receiverId int

	err = runtime.BindStyledParameterWithOptions("simple", "receiverId", chi.URLParam(r, "receiverId"), &receiverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "receiverId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, GatewayUserHeaderScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateFriendshipStatusParams

	// ------------- Required query parameter "status" -------------

	if paramValue := r.URL.Query().Get("status"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateFriendshipStatus(w, r, receiverId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGroupChat operation middleware
func (siw *ServerInterfaceWrapper) CreateGroupChat(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, GatewayUserHeaderScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGroupChat(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMessageHistory operation middleware
func (siw *ServerInterfaceWrapper) GetMessageHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "chatId" -------------
	var chatId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "chatId", chi.URLParam(r, "chatId"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chatId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, GatewayUserHeaderScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessageHistory(w, r, chatId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserInbox operation middleware
func (siw *ServerInterfaceWrapper) GetUserInbox(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, GatewayUserHeaderScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserInbox(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateReadReceipt operation middleware
func (siw *ServerInterfaceWrapper) UpdateReadReceipt(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "chatId" -------------
	var chatId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "chatId", chi.URLParam(r, "chatId"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chatId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, GatewayUserHeaderScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateReadReceipt(w, r, chatId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMessageStream operation middleware
func (siw *ServerInterfaceWrapper) GetMessageStream(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, GatewayUserHeaderScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessageStream(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendTypingEvent operation middleware
func (siw *ServerInterfaceWrapper) SendTypingEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "chatId" -------------
	var chatId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "chatId", chi.URLParam(r, "chatId"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chatId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, GatewayUserHeaderScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendTypingEvent(w, r, chatId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendMessage operation middleware
func (siw *ServerInterfaceWrapper) SendMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "chatId" -------------
	var chatId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "chatId", chi.URLParam(r, "chatId"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chatId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, GatewayUserHeaderScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendMessage(w, r, chatId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/friendship", wrapper.GetFriendList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/friendship/pending", wrapper.GetPendingFriendRequests)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/friendship/{receiverId}", wrapper.SendFriendRequest)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/friendship/{receiverId}/update", wrapper.UpdateFriendshipStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/message/group/create", wrapper.CreateGroupChat)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/message/history/{chatId}", wrapper.GetMessageHistory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/message/inbox", wrapper.GetUserInbox)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/message/read/{chatId}", wrapper.UpdateReadReceipt)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/message/stream", wrapper.GetMessageStream)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/message/typing/{chatId}", wrapper.SendTypingEvent)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/message/{chatId}", wrapper.SendMessage)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZbW/juBH+KwRb4FrAjp1s9l78Lb3N5ozeviDO4touggMtji1eJVJLUs66gf97MSQl",
	"UzZleze5K/oplkQOZ55n3jh5pJkqKyVBWkMnj9RkOZTM/fwxZ/YNGMOWgI+VVhVoK8B9zHJmpxx/LZQu",
	"maUTWteC0wG16wrohBqrhVzSzYBmSlqQFtfuf9PALPAr9xU+s7IqcMHF+OLb4fjFcPzD3fj7ycXl5OK7",
	"f9HB9ijOLAytKCF1nuDRUUJaWILG9wYkBz1Nft0MqIZPtdDA6eQjdYYEE6ONW1tize9bHdT8N8gsnoXY",
	"3SpVPgm4Eso5nuv2cTCZFpUVStIJ/VkYS9SCsKIgtQFNpq8MEZLYXBiCR5yR19rpyvG78R+sIguwWU7Y",
	"ilmmzUiyEswZHVBhoTRp2MIbpjVb4zPu2VfoF1EUZA5E1kVBFkoTLjRk1uli6IDiezZHcq2uIWGsf/FI",
	"QdYlUuD30wFdalVXEcjNlh3KWrbcshQnr7UAyRG5jrNtKaEvX47h+8vxeAgXP8yHl+f8csi+O/8WPc/t",
	"xUXnFy8GVJh3shAyWLOJ8Osju4vWByk+1UAEB2nFQoB2kNkcHF5kDvYBQLoXjl0muXvwasSR0Oc7W4VP",
	"P7uVvu8EW4P3iM/B5hALIOiCtdYgbbEmyu9rhc6VKoBJx98eRbu+9h4kF3LpmbuFTzV48rooM841GAOQ",
	"NBfxe8gV0ZCBWEEMJNFBZMrk8K3JGD1SDUh7qkRjma1N7OSVt++4d8fKDDoGt2JTLp/CrwmA1mX/rGFB",
	"J/RPo20lGIUyMEoSkCDqFhi/RYAr+8SU5+rNtCeFYzCclMDbbBB2xJJTQM2sBlZer0Kd6upfsXWhWMIL",
	"7nIgLLM1Kwhnlg2IsbrObK2BcEBuDVE+imHl/ASPHVAl4d2CTj4ehj4uv5vB4bV360rI5VRykTGr9NH1",
	"MV3H1qKrz7yLbe57YzYFDX7BIuWNn4OQSx8vXD14WIyDnQ7agHh7/cuvb65ns6ubazqgH2bXt7/e/fP9",
	"9O1N8zS7u7r7MGuebq+vXh0PngB7Q2PKiF0An+LDX9Bn7LcYKeUiBvb0Oi0xuyIiDJHqISRkojRRi0VP",
	"bo4jbZ/XOiQ/gwSiWli15BJSpWPH4DYcW733DXYQZrUWdj1DH/SG3jALD2yNWPwEjIPe1+0VrMgbxWFC",
	"3jBZs6JYEyFR5haD6StiscLiiyCRSCQUF1darQQPDREKzP1BTc9D/zGcSqvZEJUYTiNzWSX+Dmu6Qd2F",
	"XKh93a7eT12dLZlkSwyEkI+Mq+2+eJhcVNgrWWFdF4wZgMxAr0QG5Or9lA7oCrTxAs/PxmdjZEpVIFkl",
	"6IS+OBufXTpHt7nDbLSVi49LcMkN3YehWq7nuQEbNUbIlqmUNB70i/HYOf+2g2dVVWCMCCVHvxnUpLkz",
	"HCsl0SkOpy4+/ispsK9FRJgxKhPYYfuWCPtbDVYLwBJu6iwDYxZ1Ubjyc+n17IqcyhUrBG+I9+sue2q5",
	"VJYsVC05LnuZFmdBS1Y4RkCTa62Vd3BTlyXTaw9m0wg4S5BxFuJF2LwxhWhYgAaZgaObLQ3GxustWfco",
	"NmJv1DQKB1hMlWrzexLa21wk6A1rd7qk56D0SVwJmakS9ap69NsSeCJRj6HN1FO+cdlamQRdM5C821Nh",
	"1GpWggVtXGvgEhBG8jb9bEXTOKv6C9WWs70UfL/nBOf7kL3uWO7r9NdwYk6Osw4biAhhiS76CzEf1RVn",
	"1g8smM3yfew/uAVbeaGy/p4EDIK0TzXo9VacaU7uF7V7URhQlmVQWVdrOWRYQvHnvFDZv90vqTpFtW2J",
	"7tOZoEuRx4J4DL8wJkMrsGJFDb0+ENz9mdKtpzKqnqSFtNdvQt0dubHCyE9x+gP1R/f9BtdiNabttfBv",
	"iq+/KJN227YTRjvtWMcqwjjHP9i1+HHIM0xs3rLSdeetUFed6LFm2gmLZ1OJBm6z69KbdAZ6ljLUjtoS",
	"ZeemtYuEed2OT3fcyZNNGJHwsANJ8KbmPtZ1pVwYq/R69Ojb+c2hKh0k/OS3nJR12ktCf5o4cifpC/6T",
	"8T9pVtC9sO544T43rrsN0H1tHxD6qd5081b5Jc0xqcqDfcDOIqz5poJMLER2mgsIOVefD/GOxW/qFv1R",
	"VPiYOM7DLAI84gHTzzd+lky0UqVJwMaKwg94yV/CuBdbdxc5f41ap28MEcH0wyhqYLwTRQdLeDzE+CPj",
	"6Hny/4E5107GPTS5OiXVJssw434gWtmvq/ZCVrVNl2MsKAUzliCdzT03vgoJSdhpYRXmQ8fz6awZJB2J",
	"LQuf7cjNo4Zb2afVmXhEmAqj2TXJlJSQ4YsITA/leWoQz2qbKy3+A7s56V0F0hAmyY5UBFEDK9z/vsii",
	"lu41K4Tzq2NoWjfk6gZY7/XET8S8uf+zKpVwXa8XmWvFeIZeZrVYLkF/5RXSEOX+AVK6CW76UuJxI6KZ",
	"DvqB5lG4T8O52fv/lsGibaWQP4Nc2pxOzo/+my5se0LX2OUz4PeECyt6QJOlGvWSfuBqYdnylWA/Gl06",
	"DhNDy4/3boru9+6qdi15pYQMg4d2VtgdDwZniG42eME8SVBsQSSq7druN/8NAAD//4smOlkQIAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
