// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ChatRoomType.
const (
	Direct ChatRoomType = "direct"
	Group  ChatRoomType = "group"
)

// Valid indicates whether the value is a known member of the ChatRoomType enum.
func (e ChatRoomType) Valid() bool {
	switch e {
	case Direct:
		return true
	case Group:
		return true
	default:
		return false
	}
}

// Defines values for StreamEventType.
const (
	NEWMESSAGE StreamEventType = "NEW_MESSAGE"
	USERSTATUS StreamEventType = "USER_STATUS"
	USERTYPING StreamEventType = "USER_TYPING"
)

// Valid indicates whether the value is a known member of the StreamEventType enum.
func (e StreamEventType) Valid() bool {
	switch e {
	case NEWMESSAGE:
		return true
	case USERSTATUS:
		return true
	case USERTYPING:
		return true
	default:
		return false
	}
}

// Defines values for UpdateFriendshipStatusParamsStatus.
const (
	Accepted UpdateFriendshipStatusParamsStatus = "accepted"
	Blocked  UpdateFriendshipStatusParamsStatus = "blocked"
	Declined UpdateFriendshipStatusParamsStatus = "declined"
	None     UpdateFriendshipStatusParamsStatus = "none"
	Pending  UpdateFriendshipStatusParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the UpdateFriendshipStatusParamsStatus enum.
func (e UpdateFriendshipStatusParamsStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Blocked:
		return true
	case Declined:
		return true
	case None:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	ChatId    openapi_types.UUID `json:"chatId"`
	Content   string             `json:"content"`
	CreatedAt time.Time          `json:"createdAt"`
	Id        int                `json:"id"`
	SenderId  int                `json:"senderId"`
}

// ChatRoom defines model for ChatRoom.
type ChatRoom struct {
	ChatId openapi_types.UUID `json:"chatId"`

	// MemberIds List of all user IDs in this chat. Frontend uses this to fetch avatars/names.
	MemberIds *[]int `json:"memberIds,omitempty"`

	// Name Will be null for direct chats
	Name *string      `json:"name,omitempty"`
	Type ChatRoomType `json:"type"`
}

// ChatRoomType defines model for ChatRoom.Type.
type ChatRoomType string

// FriendList defines model for FriendList.
type FriendList = []struct {
	// ChatId Unique identifier for the chat between the user and the friend
	ChatId *openapi_types.UUID `json:"chatId,omitempty"`

	// FriendId Unique identifier for the friend
	FriendId *int `json:"friendId,omitempty"`
}

// StreamEvent defines model for StreamEvent.
type StreamEvent struct {
	// Payload The actual data, structure depends on the event type
	Payload StreamEvent_Payload `json:"payload"`

	// Type The type of event being sent down the stream
	Type StreamEventType `json:"type"`
}

// StreamEvent_Payload The actual data, structure depends on the event type
type StreamEvent_Payload struct {
	union json.RawMessage
}

// StreamEventType The type of event being sent down the stream
type StreamEventType string

// TypingIndicator defines model for TypingIndicator.
type TypingIndicator struct {
	ChatId   openapi_types.UUID `json:"chatId"`
	SenderId int                `json:"senderId"`
}

// UpdateFriendshipStatusParams defines parameters for UpdateFriendshipStatus.
type UpdateFriendshipStatusParams struct {
	Status UpdateFriendshipStatusParamsStatus `form:"status" json:"status"`
}

// UpdateFriendshipStatusParamsStatus defines parameters for UpdateFriendshipStatus.
type UpdateFriendshipStatusParamsStatus string

// CreateGroupChatJSONBody defines parameters for CreateGroupChat.
type CreateGroupChatJSONBody struct {
	// MemberIds List of user IDs to add to the group
	MemberIds []int `json:"memberIds"`

	// Name Name of the group chat
	Name string `json:"name"`
}

// SendMessageJSONBody defines parameters for SendMessage.
type SendMessageJSONBody struct {
	Content string `json:"content"`
}

// CreateGroupChatJSONRequestBody defines body for CreateGroupChat for application/json ContentType.
type CreateGroupChatJSONRequestBody CreateGroupChatJSONBody

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody SendMessageJSONBody

// AsChatMessage returns the union data inside the StreamEvent_Payload as a ChatMessage
func (t StreamEvent_Payload) AsChatMessage() (ChatMessage, error) {
	var body ChatMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatMessage overwrites any union data inside the StreamEvent_Payload as the provided ChatMessage
func (t *StreamEvent_Payload) FromChatMessage(v ChatMessage) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatMessage performs a merge with any union data inside the StreamEvent_Payload, using the provided ChatMessage
func (t *StreamEvent_Payload) MergeChatMessage(v ChatMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTypingIndicator returns the union data inside the StreamEvent_Payload as a TypingIndicator
func (t StreamEvent_Payload) AsTypingIndicator() (TypingIndicator, error) {
	var body TypingIndicator
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTypingIndicator overwrites any union data inside the StreamEvent_Payload as the provided TypingIndicator
func (t *StreamEvent_Payload) FromTypingIndicator(v TypingIndicator) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTypingIndicator performs a merge with any union data inside the StreamEvent_Payload, using the provided TypingIndicator
func (t *StreamEvent_Payload) MergeTypingIndicator(v TypingIndicator) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StreamEvent_Payload) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StreamEvent_Payload) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Send a friend request
	// (POST /friendship/{requesterId}/{receiverId})
	SendFriendRequest(w http.ResponseWriter, r *http.Request, requesterId int, receiverId int)
	// Update friendship status
	// (PATCH /friendship/{requesterId}/{receiverId}/update)
	UpdateFriendshipStatus(w http.ResponseWriter, r *http.Request, requesterId int, receiverId int, params UpdateFriendshipStatusParams)
	// Get friend list for a user with chat ID references
	// (GET /friendship/{tempUserId})
	GetFriendList(w http.ResponseWriter, r *http.Request, tempUserId int)
	// Create a new group chat
	// (POST /message/group/create/{tempUserId})
	CreateGroupChat(w http.ResponseWriter, r *http.Request, tempUserId int)
	// Get chat history for a specific chat
	// (GET /message/history/{chatId})
	GetMessageHistory(w http.ResponseWriter, r *http.Request, chatId openapi_types.UUID)
	// Get all chats (direct and group) for a user's inbox
	// (GET /message/inbox/{tempUserId})
	GetUserInbox(w http.ResponseWriter, r *http.Request, tempUserId int)
	// Opens an SSE connection for real-time chat message updates
	// (GET /message/stream/{tempUserId})
	GetMessageStream(w http.ResponseWriter, r *http.Request, tempUserId int)
	// Send a typing indicator event
	// (POST /message/typing/{chatId}/{tempSenderId})
	SendTypingEvent(w http.ResponseWriter, r *http.Request, chatId openapi_types.UUID, tempSenderId int)
	// Send a chat message
	// (POST /message/{chatId}/{tempSenderId})
	SendMessage(w http.ResponseWriter, r *http.Request, chatId openapi_types.UUID, tempSenderId int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Send a friend request
// (POST /friendship/{requesterId}/{receiverId})
func (_ Unimplemented) SendFriendRequest(w http.ResponseWriter, r *http.Request, requesterId int, receiverId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update friendship status
// (PATCH /friendship/{requesterId}/{receiverId}/update)
func (_ Unimplemented) UpdateFriendshipStatus(w http.ResponseWriter, r *http.Request, requesterId int, receiverId int, params UpdateFriendshipStatusParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get friend list for a user with chat ID references
// (GET /friendship/{tempUserId})
func (_ Unimplemented) GetFriendList(w http.ResponseWriter, r *http.Request, tempUserId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new group chat
// (POST /message/group/create/{tempUserId})
func (_ Unimplemented) CreateGroupChat(w http.ResponseWriter, r *http.Request, tempUserId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get chat history for a specific chat
// (GET /message/history/{chatId})
func (_ Unimplemented) GetMessageHistory(w http.ResponseWriter, r *http.Request, chatId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all chats (direct and group) for a user's inbox
// (GET /message/inbox/{tempUserId})
func (_ Unimplemented) GetUserInbox(w http.ResponseWriter, r *http.Request, tempUserId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Opens an SSE connection for real-time chat message updates
// (GET /message/stream/{tempUserId})
func (_ Unimplemented) GetMessageStream(w http.ResponseWriter, r *http.Request, tempUserId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send a typing indicator event
// (POST /message/typing/{chatId}/{tempSenderId})
func (_ Unimplemented) SendTypingEvent(w http.ResponseWriter, r *http.Request, chatId openapi_types.UUID, tempSenderId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send a chat message
// (POST /message/{chatId}/{tempSenderId})
func (_ Unimplemented) SendMessage(w http.ResponseWriter, r *http.Request, chatId openapi_types.UUID, tempSenderId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SendFriendRequest operation middleware
func (siw *ServerInterfaceWrapper) SendFriendRequest(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "requesterId" -------------
	var requesterId int

	err = runtime.BindStyledParameterWithOptions("simple", "requesterId", chi.URLParam(r, "requesterId"), &requesterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "requesterId", Err: err})
		return
	}

	// ------------- Path parameter "receiverId" -------------
	var receiverId int

	err = runtime.BindStyledParameterWithOptions("simple", "receiverId", chi.URLParam(r, "receiverId"), &receiverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "receiverId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendFriendRequest(w, r, requesterId, receiverId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateFriendshipStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateFriendshipStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "requesterId" -------------
	var requesterId int

	err = runtime.BindStyledParameterWithOptions("simple", "requesterId", chi.URLParam(r, "requesterId"), &requesterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "requesterId", Err: err})
		return
	}

	// ------------- Path parameter "receiverId" -------------
	var receiverId int

	err = runtime.BindStyledParameterWithOptions("simple", "receiverId", chi.URLParam(r, "receiverId"), &receiverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "receiverId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateFriendshipStatusParams

	// ------------- Required query parameter "status" -------------

	if paramValue := r.URL.Query().Get("status"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateFriendshipStatus(w, r, requesterId, receiverId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFriendList operation middleware
func (siw *ServerInterfaceWrapper) GetFriendList(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tempUserId" -------------
	var tempUserId int

	err = runtime.BindStyledParameterWithOptions("simple", "tempUserId", chi.URLParam(r, "tempUserId"), &tempUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tempUserId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFriendList(w, r, tempUserId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGroupChat operation middleware
func (siw *ServerInterfaceWrapper) CreateGroupChat(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tempUserId" -------------
	var tempUserId int

	err = runtime.BindStyledParameterWithOptions("simple", "tempUserId", chi.URLParam(r, "tempUserId"), &tempUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tempUserId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGroupChat(w, r, tempUserId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMessageHistory operation middleware
func (siw *ServerInterfaceWrapper) GetMessageHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "chatId" -------------
	var chatId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "chatId", chi.URLParam(r, "chatId"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chatId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessageHistory(w, r, chatId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserInbox operation middleware
func (siw *ServerInterfaceWrapper) GetUserInbox(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tempUserId" -------------
	var tempUserId int

	err = runtime.BindStyledParameterWithOptions("simple", "tempUserId", chi.URLParam(r, "tempUserId"), &tempUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tempUserId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserInbox(w, r, tempUserId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMessageStream operation middleware
func (siw *ServerInterfaceWrapper) GetMessageStream(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tempUserId" -------------
	var tempUserId int

	err = runtime.BindStyledParameterWithOptions("simple", "tempUserId", chi.URLParam(r, "tempUserId"), &tempUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tempUserId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMessageStream(w, r, tempUserId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendTypingEvent operation middleware
func (siw *ServerInterfaceWrapper) SendTypingEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "chatId" -------------
	var chatId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "chatId", chi.URLParam(r, "chatId"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chatId", Err: err})
		return
	}

	// ------------- Path parameter "tempSenderId" -------------
	var tempSenderId int

	err = runtime.BindStyledParameterWithOptions("simple", "tempSenderId", chi.URLParam(r, "tempSenderId"), &tempSenderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tempSenderId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendTypingEvent(w, r, chatId, tempSenderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendMessage operation middleware
func (siw *ServerInterfaceWrapper) SendMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "chatId" -------------
	var chatId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "chatId", chi.URLParam(r, "chatId"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chatId", Err: err})
		return
	}

	// ------------- Path parameter "tempSenderId" -------------
	var tempSenderId int

	err = runtime.BindStyledParameterWithOptions("simple", "tempSenderId", chi.URLParam(r, "tempSenderId"), &tempSenderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tempSenderId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendMessage(w, r, chatId, tempSenderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/friendship/{requesterId}/{receiverId}", wrapper.SendFriendRequest)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/friendship/{requesterId}/{receiverId}/update", wrapper.UpdateFriendshipStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/friendship/{tempUserId}", wrapper.GetFriendList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/message/group/create/{tempUserId}", wrapper.CreateGroupChat)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/message/history/{chatId}", wrapper.GetMessageHistory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/message/inbox/{tempUserId}", wrapper.GetUserInbox)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/message/stream/{tempUserId}", wrapper.GetMessageStream)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/message/typing/{chatId}/{tempSenderId}", wrapper.SendTypingEvent)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/message/{chatId}/{tempSenderId}", wrapper.SendMessage)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RY7W7buBJ9FYL3Ar0XUGInTb/8L9t1swbatKgTFLtFUNDi2GZXIlVy5NQb+N0XQ0qy",
	"bNOxU3c/+suWRA5n5hwezvCOpyYvjAaNjvfuuEunkAv/9+VU4BtwTkyAHgtrCrCowH9MpwIHkv6Njc0F",
	"8h4vSyV5wnFeAO9xh1bpCV8kPDUaQSON3fxmQSDIc/8Vvoq8yGjAaff06VH38VH3xVX3ee/0rHf67Dee",
	"LJeSAuEIVQ6x9ZRsLaU0wgQsvXegJdhB9Osi4Ra+lMqC5L2P3AdShdiauIyl7flN44MZfYYUaS3K3Xtj",
	"8oMSl0M+onX9PAkutapAZTTv8dfKITNjJrKMlQ4sG/zsmNIMp8oxWuKYvbLeV0nfXfiAho0B0ykTM4HC",
	"uo4WObhjnnCFkLt42qo3wloxp2eas+nQB5VlbARMl1nGxsYyqSyk6H1xPOH0XowIXLQlRIINL+446DIn",
	"CMJ8nvCJNWXRSnI9ZQ2yBi0/LIbJK6tAS8rcCtmWkPAnT7rw/KzbPYLTF6OjsxN5diSenTwl5vm5NOjk",
	"9PGila9t4K5m51qrLyUwJUGjGiuwPkU4BZ8fNgK8BdD+hUdTaOkfwrJt5m/jytLB/ddurEd2w0b21mkw",
	"RAsi78+qnb2ah0LMMyMizlxNgYkUS5ExKVAkzKEtUywtMAkFaOmYCXkAssz8qgk3Gt6Oee/jHf+vhTHv",
	"8f90lrLVqTSr0xasRXL/2Kt5ofRkoKVKBRrLFzdbY47FQF9o/wUvR6D0hDn6K81t8N/5/PCkIfRl/8On",
	"N/3h8PyizxN+Pey//3T167vB5UX9NLw6v7oe7mZ6lZM6xzHH16M7RIUeIJubirnpHM1Remw283r+buCp",
	"mQstJpTQPGDp/HYIZHVTVZCcoEJ/UBDkbAh2plJg5+8GPOEzsC4YPDnuHncpBFOAFoXiPf74uHt85pOH",
	"U5+IztJu545iAYfk+YKeUlAz/+ATaIJwUBoFuewlYwhaBmF5HyZ741bkgGCdp6wiX2hBXosnby3E2ykM",
	"2hg4Gs/3FnO1pw+zdkOjXWG0C6w47Z5swhKiY5XLgeWuTFNwblxmmReDs253c+JAz0SmZHM+hYFnEYWi",
	"AdogG5tSS88qV+a5sPMqwUxU8NdeEAPEhNJbuUf48RuauR+gnbKgGiJoFabTTWCv/YCl9SEKLN2PhG5t",
	"7UsJdr405+pAtpuqJYsEmVQg4SJNoUAgDySkmdL+7ygz6e/+nzYaYsq1ybAIUUJqWYBEPoxcIRo2E1kJ",
	"WwlWbc02xxL+JG4WwWqReU0By/rWGrvGyMCMliCxJqV7kRIhL4jyla5MICIrF4CtcmUf0i2tHqoBPi2t",
	"ol0URUbniDK689lRmu5aBu87ZFsheN2PCktGpSwpvHDOpMpTwFdFVNJaQKtg9lBWVJKzt+IcwIYLwFqc",
	"fCR0gongwK3CaR0KszAGCzqFe3lSHXkdX/R2Qo+xwZj4SfTSD76giXQq/vWk8XvqJyPnD+LLah2yR4vT",
	"tDdomJCSfqi+Cm3Bd+hcLkXuS7nGqIeM76rCvLF2jxYvdVaTuogfuN9lszUtZ2SrXTRxsapvXdtPK5QO",
	"TGKCabhdS0nF27rKXiXtVDk0dt65C3XgvepWWfglTNmLrE11uZ2oO4rZg8WuIdv+bcgaCzex8SVslbpv",
	"1btKZLbq3aUJQ+plYoUWCdnaIFIyV0CqxirdjwJKj8zXvY84P4Rm/KtPuL1BD7tvN+LDFrQtxEnoHoXb",
	"G2aNyV0EIJFl4UqF/a+6YKGT0+/R/7eOnkeOqSqv9+MVutS9AauMDOve9p8EDeErdnz/fVT12ntLZfvu",
	"IobPsM9SozWk9KK1E8P+OondsYgSp8aqP2B9W70tQFMHy9asElgWROavMQPoFShVIex2goe+y2/kNqA4",
	"rFrvHT1ruCEIKfibxDfZSpDh8oL1IIpElC/EyUbWCJkKhwytmkzAfmNF6Zjx92e5v76Kt6oBFqbq25dw",
	"SbQTzW+CsTb1I0P4PerI1rRc6degJzjlvZOdl8bVtANqt1W6VHgccEtCBKuFoHYvSrO2ZMTJtWjeri/a",
	"17IwSqNbvXBbvWOr0G31KIT/XobavrVMNVXRzeLPAAAA///UZz81eBoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
