global:
    scrape_interval: 15s # How often to pull. 15s is the industry standard.
    evaluation_interval: 15s # How often to check your "Alert" rules.

scrape_configs:
    - job_name: 'gateway' # A label added to EVERY metric from this job.

      # The 'metrics_path' is relative to the target's root.
      # Quarkus management defaults to /q/metrics, but you set it to /metrics.
      metrics_path: '/metrics'

      static_configs:
          - targets: ['gateway-service:8180'] # 'host:port' inside Docker.
            labels:
                env: 'production' # You can add custom labels to ALL metrics here!
