// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friendship_queries.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkChatPermissions = `-- name: CheckChatPermissions :one
SELECT
    r.type AS room_type,
    f.is_chat_allowed
FROM chat_service.rooms r
JOIN chat_service.room_members me ON r.id = me.chat_id
LEFT JOIN chat_service.room_members other
    ON r.id = other.chat_id
    AND me.user_id != other.user_id
    AND r.type = 'direct'
LEFT JOIN chat_service.friendships f
    ON r.type = 'direct' AND (
        (f.requester_id = me.user_id AND f.addressee_id = other.user_id) OR
        (f.requester_id = other.user_id AND f.addressee_id = me.user_id)
    )
WHERE r.id = $1
  AND me.user_id = $2
LIMIT 1
`

type CheckChatPermissionsParams struct {
	ID     uuid.UUID `json:"id"`
	UserID int32     `json:"userId"`
}

type CheckChatPermissionsRow struct {
	RoomType      string       `json:"roomType"`
	IsChatAllowed sql.NullBool `json:"isChatAllowed"`
}

// Only attempt to find the "other" person if it's a direct chat
// Only attempt to join friendships if it's a direct chat
func (q *Queries) CheckChatPermissions(ctx context.Context, arg CheckChatPermissionsParams) (CheckChatPermissionsRow, error) {
	row := q.db.QueryRowContext(ctx, checkChatPermissions, arg.ID, arg.UserID)
	var i CheckChatPermissionsRow
	err := row.Scan(&i.RoomType, &i.IsChatAllowed)
	return i, err
}

const createDirectRoomWithMembers = `-- name: CreateDirectRoomWithMembers :one
WITH existing_room AS (
    SELECT rm1.chat_id
    FROM chat_service.room_members rm1
    JOIN chat_service.room_members rm2 ON rm1.chat_id = rm2.chat_id
    JOIN chat_service.rooms r ON rm1.chat_id = r.id
    WHERE r.type = 'direct'
      AND rm1.user_id = $1
      AND rm2.user_id = $2
    LIMIT 1
),
new_room AS (
    INSERT INTO chat_service.rooms (type, name)
    SELECT 'direct', NULL
    WHERE NOT EXISTS (SELECT 1 FROM existing_room)
    RETURNING id
),
inserted_members AS (
    INSERT INTO chat_service.room_members (chat_id, user_id, role)
    SELECT id, $1, 'member' FROM new_room
    UNION ALL
    SELECT id, $2, 'member' FROM new_room
    RETURNING chat_id
)
SELECT chat_id FROM inserted_members
UNION ALL
SELECT chat_id FROM existing_room
LIMIT 1
`

type CreateDirectRoomWithMembersParams struct {
	UserID   int32 `json:"userId"`
	UserID_2 int32 `json:"userId2"`
}

func (q *Queries) CreateDirectRoomWithMembers(ctx context.Context, arg CreateDirectRoomWithMembersParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createDirectRoomWithMembers, arg.UserID, arg.UserID_2)
	var chat_id uuid.UUID
	err := row.Scan(&chat_id)
	return chat_id, err
}

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO chat_service.friendships (requester_id, addressee_id, last_action_user_id, status)
VALUES ($1, $2, $3, 'pending')
RETURNING requester_id, addressee_id, last_action_user_id, is_chat_allowed, status, created_at, updated_at
`

type CreateFriendshipParams struct {
	RequesterID      int32 `json:"requesterId"`
	AddresseeID      int32 `json:"addresseeId"`
	LastActionUserID int32 `json:"lastActionUserId"`
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (ChatServiceFriendship, error) {
	row := q.db.QueryRowContext(ctx, createFriendship, arg.RequesterID, arg.AddresseeID, arg.LastActionUserID)
	var i ChatServiceFriendship
	err := row.Scan(
		&i.RequesterID,
		&i.AddresseeID,
		&i.LastActionUserID,
		&i.IsChatAllowed,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessageRequestFriendship = `-- name: CreateMessageRequestFriendship :one
INSERT INTO chat_service.friendships (requester_id, addressee_id, last_action_user_id, status, is_chat_allowed)
VALUES ($1, $2, $3, 'requested', false)
RETURNING requester_id, addressee_id, last_action_user_id, is_chat_allowed, status, created_at, updated_at
`

type CreateMessageRequestFriendshipParams struct {
	RequesterID      int32 `json:"requesterId"`
	AddresseeID      int32 `json:"addresseeId"`
	LastActionUserID int32 `json:"lastActionUserId"`
}

func (q *Queries) CreateMessageRequestFriendship(ctx context.Context, arg CreateMessageRequestFriendshipParams) (ChatServiceFriendship, error) {
	row := q.db.QueryRowContext(ctx, createMessageRequestFriendship, arg.RequesterID, arg.AddresseeID, arg.LastActionUserID)
	var i ChatServiceFriendship
	err := row.Scan(
		&i.RequesterID,
		&i.AddresseeID,
		&i.LastActionUserID,
		&i.IsChatAllowed,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFriendListWithChatIds = `-- name: GetFriendListWithChatIds :many
WITH friends AS (
    SELECT addressee_id AS friend_id
    FROM chat_service.friendships
    WHERE requester_id = $1 AND status = 'accepted'
    UNION
    SELECT requester_id AS friend_id
    FROM chat_service.friendships
    WHERE addressee_id = $1 AND status = 'accepted'
)
SELECT
    f.friend_id,
    -- 2. Find the direct chat room shared by the user and this specific friend
    (
        SELECT rm_friend.chat_id
        FROM chat_service.room_members rm_friend
        JOIN chat_service.rooms r ON r.id = rm_friend.chat_id
        JOIN chat_service.room_members rm_me ON rm_me.chat_id = r.id
        WHERE r.type = 'direct'
          AND rm_me.user_id = $1
          AND rm_friend.user_id = f.friend_id
        LIMIT 1
    ) AS chat_id
FROM friends f
`

type GetFriendListWithChatIdsRow struct {
	FriendID int32     `json:"friendId"`
	ChatID   uuid.UUID `json:"chatId"`
}

func (q *Queries) GetFriendListWithChatIds(ctx context.Context, userID int32) ([]GetFriendListWithChatIdsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFriendListWithChatIds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendListWithChatIdsRow
	for rows.Next() {
		var i GetFriendListWithChatIdsRow
		if err := rows.Scan(&i.FriendID, &i.ChatID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendship = `-- name: GetFriendship :one
SELECT requester_id, addressee_id, last_action_user_id, is_chat_allowed, status, created_at, updated_at FROM chat_service.friendships
WHERE (requester_id = $1 AND addressee_id = $2)
   OR (requester_id = $2 AND addressee_id = $1)
LIMIT 1
`

type GetFriendshipParams struct {
	RequesterID int32 `json:"requesterId"`
	AddresseeID int32 `json:"addresseeId"`
}

func (q *Queries) GetFriendship(ctx context.Context, arg GetFriendshipParams) (ChatServiceFriendship, error) {
	row := q.db.QueryRowContext(ctx, getFriendship, arg.RequesterID, arg.AddresseeID)
	var i ChatServiceFriendship
	err := row.Scan(
		&i.RequesterID,
		&i.AddresseeID,
		&i.LastActionUserID,
		&i.IsChatAllowed,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingFriendRequests = `-- name: GetPendingFriendRequests :many
SELECT requester_id, addressee_id, status
FROM chat_service.friendships
WHERE addressee_id = $1
    AND status = 'pending'
ORDER BY requester_id ASC
`

type GetPendingFriendRequestsRow struct {
	RequesterID int32                       `json:"requesterId"`
	AddresseeID int32                       `json:"addresseeId"`
	Status      NullChatServiceFriendStatus `json:"status"`
}

func (q *Queries) GetPendingFriendRequests(ctx context.Context, addresseeID int32) ([]GetPendingFriendRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingFriendRequests, addresseeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingFriendRequestsRow
	for rows.Next() {
		var i GetPendingFriendRequestsRow
		if err := rows.Scan(&i.RequesterID, &i.AddresseeID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFriendshipStatus = `-- name: UpdateFriendshipStatus :one
UPDATE chat_service.friendships
SET status = $3, last_action_user_id = $4, is_chat_allowed = $5, updated_at = CURRENT_TIMESTAMP
WHERE (requester_id = $1 AND addressee_id = $2)
   OR (requester_id = $2 AND addressee_id = $1)
RETURNING requester_id, addressee_id, last_action_user_id, is_chat_allowed, status, created_at, updated_at
`

type UpdateFriendshipStatusParams struct {
	RequesterID      int32                       `json:"requesterId"`
	AddresseeID      int32                       `json:"addresseeId"`
	Status           NullChatServiceFriendStatus `json:"status"`
	LastActionUserID int32                       `json:"lastActionUserId"`
	IsChatAllowed    sql.NullBool                `json:"isChatAllowed"`
}

func (q *Queries) UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) (ChatServiceFriendship, error) {
	row := q.db.QueryRowContext(ctx, updateFriendshipStatus,
		arg.RequesterID,
		arg.AddresseeID,
		arg.Status,
		arg.LastActionUserID,
		arg.IsChatAllowed,
	)
	var i ChatServiceFriendship
	err := row.Scan(
		&i.RequesterID,
		&i.AddresseeID,
		&i.LastActionUserID,
		&i.IsChatAllowed,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
