// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friendship_queries.sql

package database

import (
	"context"
)

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO chat_service.friendships (requester_id, addressee_id, status)
VALUES ($1, $2, 'PENDING')
RETURNING requester_id, addressee_id, status, created_at, updated_at
`

type CreateFriendshipParams struct {
	RequesterID int32
	AddresseeID int32
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (ChatServiceFriendship, error) {
	row := q.db.QueryRow(ctx, createFriendship, arg.RequesterID, arg.AddresseeID)
	var i ChatServiceFriendship
	err := row.Scan(
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFriendshipStatus = `-- name: UpdateFriendshipStatus :exec
UPDATE chat_service.friendships
SET status = $3, updated_at = CURRENT_TIMESTAMP
WHERE requester_id = $1 AND addressee_id = $2
`

type UpdateFriendshipStatusParams struct {
	RequesterID int32
	AddresseeID int32
	Status      NullChatServiceFriendStatus
}

func (q *Queries) UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) error {
	_, err := q.db.Exec(ctx, updateFriendshipStatus, arg.RequesterID, arg.AddresseeID, arg.Status)
	return err
}
