// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message_queries.sql

package database

import (
	"context"
)

const getChatHistory = `-- name: GetChatHistory :many
SELECT id, sender_id, receiver_id, content, is_read, read_at, created_at
FROM chat_service.messages
WHERE (sender_id = $1 AND receiver_id = $2)
 OR (sender_id = $2 AND receiver_id = $1)
ORDER BY created_at ASC
`

type GetChatHistoryParams struct {
	SenderID   int32
	ReceiverID int32
}

func (q *Queries) GetChatHistory(ctx context.Context, arg GetChatHistoryParams) ([]ChatServiceMessage, error) {
	rows, err := q.db.Query(ctx, getChatHistory, arg.SenderID, arg.ReceiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatServiceMessage
	for rows.Next() {
		var i ChatServiceMessage
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Content,
			&i.IsRead,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendMessage = `-- name: SendMessage :one
INSERT INTO chat_service.messages (sender_id, receiver_id, content)
VALUES ($1, $2, $3)
RETURNING id, sender_id, receiver_id, content, is_read, read_at, created_at
`

type SendMessageParams struct {
	SenderID   int32
	ReceiverID int32
	Content    string
}

func (q *Queries) SendMessage(ctx context.Context, arg SendMessageParams) (ChatServiceMessage, error) {
	row := q.db.QueryRow(ctx, sendMessage, arg.SenderID, arg.ReceiverID, arg.Content)
	var i ChatServiceMessage
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}
