// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message_queries.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createGroupChatRoom = `-- name: CreateGroupChatRoom :one
INSERT INTO chat_service.rooms (type, name)
VALUES ('group', $1)
RETURNING id, type, name
`

type CreateGroupChatRoomRow struct {
	ID   uuid.UUID      `json:"id"`
	Type string         `json:"type"`
	Name sql.NullString `json:"name"`
}

func (q *Queries) CreateGroupChatRoom(ctx context.Context, name sql.NullString) (CreateGroupChatRoomRow, error) {
	row := q.db.QueryRowContext(ctx, createGroupChatRoom, name)
	var i CreateGroupChatRoomRow
	err := row.Scan(&i.ID, &i.Type, &i.Name)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO chat_service.messages (chat_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, chat_id, sender_id, content, created_at
`

type CreateMessageParams struct {
	ChatID   uuid.UUID `json:"chatId"`
	SenderID int32     `json:"senderId"`
	Content  string    `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (ChatServiceMessage, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.ChatID, arg.SenderID, arg.Content)
	var i ChatServiceMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createRoomMembersForGroupChat = `-- name: CreateRoomMembersForGroupChat :exec
INSERT INTO chat_service.room_members (chat_id, user_id, role)
SELECT
    $1::uuid,
    $2::int,
    'admin'
UNION ALL
SELECT
    $1::uuid,
    u_id,
    'member'
FROM unnest($3::int[]) AS u_id
WHERE u_id <> $2::int
`

type CreateRoomMembersForGroupChatParams struct {
	Column1 uuid.UUID `json:"column1"`
	Column2 int32     `json:"column2"`
	Column3 []int32   `json:"column3"`
}

func (q *Queries) CreateRoomMembersForGroupChat(ctx context.Context, arg CreateRoomMembersForGroupChatParams) error {
	_, err := q.db.ExecContext(ctx, createRoomMembersForGroupChat, arg.Column1, arg.Column2, pq.Array(arg.Column3))
	return err
}

const getMessageHistoryByChatId = `-- name: GetMessageHistoryByChatId :many
SELECT m.id, m.chat_id, m.sender_id, m.content, m.created_at
FROM chat_service.messages m
LEFT JOIN chat_service.friendships f
  ON (f.requester_id = m.sender_id AND f.addressee_id = $2)
  OR (f.requester_id = $2 AND f.addressee_id = m.sender_id)
WHERE m.chat_id = $1
  AND (f.status IS NULL OR f.status != 'blocked')
ORDER BY m.created_at DESC
`

type GetMessageHistoryByChatIdParams struct {
	ChatID      uuid.UUID `json:"chatId"`
	AddresseeID int32     `json:"addresseeId"`
}

func (q *Queries) GetMessageHistoryByChatId(ctx context.Context, arg GetMessageHistoryByChatIdParams) ([]ChatServiceMessage, error) {
	rows, err := q.db.QueryContext(ctx, getMessageHistoryByChatId, arg.ChatID, arg.AddresseeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatServiceMessage
	for rows.Next() {
		var i ChatServiceMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomMemberIDs = `-- name: GetRoomMemberIDs :many
SELECT user_id
FROM chat_service.room_members
WHERE chat_id = $1
`

func (q *Queries) GetRoomMemberIDs(ctx context.Context, chatID uuid.UUID) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getRoomMemberIDs, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var user_id int32
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserInbox = `-- name: GetUserInbox :many
SELECT
    c.id AS chat_id,
    c.type,
    c.name,
    array_agg(rm.user_id)::integer[] AS member_ids,
    CASE
        WHEN c.type = 'group' THEN true
        ELSE COALESCE(
            (SELECT f.is_chat_allowed
             FROM chat_service.room_members rm_other
             JOIN chat_service.friendships f
               ON (f.requester_id = $1 AND f.addressee_id = rm_other.user_id)
               OR (f.requester_id = rm_other.user_id AND f.addressee_id = $1)
             WHERE rm_other.chat_id = c.id
               AND rm_other.user_id != $1
             LIMIT 1),
            false
        )
    END::boolean AS is_allowed_chat,

    COALESCE(
        CASE
            WHEN c.type = 'group' THEN NULL::integer
            ELSE (
                SELECT f.last_action_user_id
                FROM chat_service.room_members rm_other
                JOIN chat_service.friendships f
                ON (f.requester_id = $1 AND f.addressee_id = rm_other.user_id)
                OR (f.requester_id = rm_other.user_id AND f.addressee_id = $1)
                WHERE rm_other.chat_id = c.id
                AND rm_other.user_id != $1
                LIMIT 1
            )
        END,
        0
    )::int AS requested_by,

	(
        SELECT f.status
        FROM chat_service.room_members rm_other
        JOIN chat_service.friendships f
        ON (f.requester_id = $1 AND f.addressee_id = rm_other.user_id)
        OR (f.requester_id = rm_other.user_id AND f.addressee_id = $1)
        WHERE rm_other.chat_id = c.id
        AND rm_other.user_id != $1
        AND c.type != 'group' -- Moved your CASE logic into the WHERE clause
        LIMIT 1
    ) AS friendship_status

FROM chat_service.rooms c
JOIN chat_service.room_members rm ON c.id = rm.chat_id
WHERE c.id IN (
    SELECT rm_sub.chat_id
    FROM chat_service.room_members rm_sub
    WHERE rm_sub.user_id = $1
)
AND NOT (
    c.type = 'direct' AND EXISTS (
        SELECT 1
        FROM chat_service.room_members rm_other
        JOIN chat_service.friendships f
          ON (f.requester_id = $1 AND f.addressee_id = rm_other.user_id)
          OR (f.requester_id = rm_other.user_id AND f.addressee_id = $1)
        WHERE rm_other.chat_id = c.id
          AND rm_other.user_id != $1
          AND f.status = 'blocked'
    )
)
GROUP BY c.id, c.type, c.name
`

type GetUserInboxRow struct {
	ChatID           uuid.UUID                   `json:"chatId"`
	Type             string                      `json:"type"`
	Name             sql.NullString              `json:"name"`
	MemberIds        []int32                     `json:"memberIds"`
	IsAllowedChat    bool                        `json:"isAllowedChat"`
	RequestedBy      int32                       `json:"requestedBy"`
	FriendshipStatus NullChatServiceFriendStatus `json:"friendshipStatus"`
}

func (q *Queries) GetUserInbox(ctx context.Context, requesterID int32) ([]GetUserInboxRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserInbox, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserInboxRow
	for rows.Next() {
		var i GetUserInboxRow
		if err := rows.Scan(
			&i.ChatID,
			&i.Type,
			&i.Name,
			pq.Array(&i.MemberIds),
			&i.IsAllowedChat,
			&i.RequestedBy,
			&i.FriendshipStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastReadMessageID = `-- name: UpdateLastReadMessageID :exec
UPDATE chat_service.room_members
SET last_read_message_id = GREATEST(COALESCE(last_read_message_id, 0), $1)
WHERE chat_id = $2 AND user_id = $3
`

type UpdateLastReadMessageIDParams struct {
	LastReadMessageID sql.NullInt64 `json:"lastReadMessageId"`
	ChatID            uuid.UUID     `json:"chatId"`
	UserID            int32         `json:"userId"`
}

func (q *Queries) UpdateLastReadMessageID(ctx context.Context, arg UpdateLastReadMessageIDParams) error {
	_, err := q.db.ExecContext(ctx, updateLastReadMessageID, arg.LastReadMessageID, arg.ChatID, arg.UserID)
	return err
}
