// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type ChatServiceFriendStatus string

const (
	ChatServiceFriendStatusRequested ChatServiceFriendStatus = "requested"
	ChatServiceFriendStatusPending   ChatServiceFriendStatus = "pending"
	ChatServiceFriendStatusBlocked   ChatServiceFriendStatus = "blocked"
	ChatServiceFriendStatusAccepted  ChatServiceFriendStatus = "accepted"
)

func (e *ChatServiceFriendStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatServiceFriendStatus(s)
	case string:
		*e = ChatServiceFriendStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatServiceFriendStatus: %T", src)
	}
	return nil
}

type NullChatServiceFriendStatus struct {
	ChatServiceFriendStatus ChatServiceFriendStatus `json:"chatServiceFriendStatus"`
	Valid                   bool                    `json:"valid"` // Valid is true if ChatServiceFriendStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatServiceFriendStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ChatServiceFriendStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatServiceFriendStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatServiceFriendStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatServiceFriendStatus), nil
}

type ChatServiceFriendship struct {
	RequesterID      int32                       `json:"requesterId"`
	AddresseeID      int32                       `json:"addresseeId"`
	LastActionUserID int32                       `json:"lastActionUserId"`
	IsChatAllowed    sql.NullBool                `json:"isChatAllowed"`
	Status           NullChatServiceFriendStatus `json:"status"`
	CreatedAt        sql.NullTime                `json:"createdAt"`
	UpdatedAt        sql.NullTime                `json:"updatedAt"`
}

type ChatServiceMessage struct {
	ID        int64        `json:"id"`
	ChatID    uuid.UUID    `json:"chatId"`
	SenderID  int32        `json:"senderId"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"createdAt"`
}

type ChatServiceRoom struct {
	ID        uuid.UUID      `json:"id"`
	Type      string         `json:"type"`
	Name      sql.NullString `json:"name"`
	CreatedAt sql.NullTime   `json:"createdAt"`
}

type ChatServiceRoomMember struct {
	ChatID            uuid.UUID      `json:"chatId"`
	UserID            int32          `json:"userId"`
	Role              sql.NullString `json:"role"`
	JoinedAt          sql.NullTime   `json:"joinedAt"`
	LastReadMessageID sql.NullInt64  `json:"lastReadMessageId"`
}
