// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChatServiceFriendStatus string

const (
	ChatServiceFriendStatusPending  ChatServiceFriendStatus = "pending"
	ChatServiceFriendStatusAccepted ChatServiceFriendStatus = "accepted"
	ChatServiceFriendStatusBlocked  ChatServiceFriendStatus = "blocked"
	ChatServiceFriendStatusDeclined ChatServiceFriendStatus = "declined"
	ChatServiceFriendStatusNone     ChatServiceFriendStatus = "none"
)

func (e *ChatServiceFriendStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatServiceFriendStatus(s)
	case string:
		*e = ChatServiceFriendStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatServiceFriendStatus: %T", src)
	}
	return nil
}

type NullChatServiceFriendStatus struct {
	ChatServiceFriendStatus ChatServiceFriendStatus
	Valid                   bool // Valid is true if ChatServiceFriendStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatServiceFriendStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ChatServiceFriendStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatServiceFriendStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatServiceFriendStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatServiceFriendStatus), nil
}

type ChatServiceFriendship struct {
	ChatID      pgtype.UUID
	RequesterID int32
	AddresseeID int32
	Status      NullChatServiceFriendStatus
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ChatServiceMessage struct {
	ID         int64
	ChatID     pgtype.UUID
	SenderID   int32
	ReceiverID int32
	Content    string
	IsRead     pgtype.Bool
	ReadAt     pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}
