// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChatServiceFriendStatus string

const (
	ChatServiceFriendStatusPending  ChatServiceFriendStatus = "pending"
	ChatServiceFriendStatusAccepted ChatServiceFriendStatus = "accepted"
	ChatServiceFriendStatusBlocked  ChatServiceFriendStatus = "blocked"
	ChatServiceFriendStatusDeclined ChatServiceFriendStatus = "declined"
	ChatServiceFriendStatusNone     ChatServiceFriendStatus = "none"
)

func (e *ChatServiceFriendStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatServiceFriendStatus(s)
	case string:
		*e = ChatServiceFriendStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatServiceFriendStatus: %T", src)
	}
	return nil
}

type NullChatServiceFriendStatus struct {
	ChatServiceFriendStatus ChatServiceFriendStatus `json:"chatServiceFriendStatus"`
	Valid                   bool                    `json:"valid"` // Valid is true if ChatServiceFriendStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatServiceFriendStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ChatServiceFriendStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatServiceFriendStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatServiceFriendStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatServiceFriendStatus), nil
}

type ChatServiceFriendship struct {
	ChatID      pgtype.UUID                 `json:"chatId"`
	RequesterID int32                       `json:"requesterId"`
	AddresseeID int32                       `json:"addresseeId"`
	Status      NullChatServiceFriendStatus `json:"status"`
	CreatedAt   pgtype.Timestamptz          `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz          `json:"updatedAt"`
}

type ChatServiceMessage struct {
	ID         int64              `json:"id"`
	ChatID     pgtype.UUID        `json:"chatId"`
	SenderID   int32              `json:"senderId"`
	ReceiverID int32              `json:"receiverId"`
	Content    string             `json:"content"`
	IsRead     pgtype.Bool        `json:"isRead"`
	ReadAt     pgtype.Timestamptz `json:"readAt"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}
